package com.suse.hl.clazzmenoir.common.domain;

import java.util.ArrayList;
import java.util.List;

public class ClazzExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public ClazzExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCIdIsNull() {
            addCriterion("c_id is null");
            return (Criteria) this;
        }

        public Criteria andCIdIsNotNull() {
            addCriterion("c_id is not null");
            return (Criteria) this;
        }

        public Criteria andCIdEqualTo(String value) {
            addCriterion("c_id =", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotEqualTo(String value) {
            addCriterion("c_id <>", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThan(String value) {
            addCriterion("c_id >", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdGreaterThanOrEqualTo(String value) {
            addCriterion("c_id >=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThan(String value) {
            addCriterion("c_id <", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLessThanOrEqualTo(String value) {
            addCriterion("c_id <=", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdLike(String value) {
            addCriterion("c_id like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotLike(String value) {
            addCriterion("c_id not like", value, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdIn(List<String> values) {
            addCriterion("c_id in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotIn(List<String> values) {
            addCriterion("c_id not in", values, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdBetween(String value1, String value2) {
            addCriterion("c_id between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCIdNotBetween(String value1, String value2) {
            addCriterion("c_id not between", value1, value2, "cId");
            return (Criteria) this;
        }

        public Criteria andCNameIsNull() {
            addCriterion("c_name is null");
            return (Criteria) this;
        }

        public Criteria andCNameIsNotNull() {
            addCriterion("c_name is not null");
            return (Criteria) this;
        }

        public Criteria andCNameEqualTo(String value) {
            addCriterion("c_name =", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotEqualTo(String value) {
            addCriterion("c_name <>", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThan(String value) {
            addCriterion("c_name >", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameGreaterThanOrEqualTo(String value) {
            addCriterion("c_name >=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThan(String value) {
            addCriterion("c_name <", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLessThanOrEqualTo(String value) {
            addCriterion("c_name <=", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameLike(String value) {
            addCriterion("c_name like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotLike(String value) {
            addCriterion("c_name not like", value, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameIn(List<String> values) {
            addCriterion("c_name in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotIn(List<String> values) {
            addCriterion("c_name not in", values, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameBetween(String value1, String value2) {
            addCriterion("c_name between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNameNotBetween(String value1, String value2) {
            addCriterion("c_name not between", value1, value2, "cName");
            return (Criteria) this;
        }

        public Criteria andCNumberIsNull() {
            addCriterion("c_number is null");
            return (Criteria) this;
        }

        public Criteria andCNumberIsNotNull() {
            addCriterion("c_number is not null");
            return (Criteria) this;
        }

        public Criteria andCNumberEqualTo(Integer value) {
            addCriterion("c_number =", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberNotEqualTo(Integer value) {
            addCriterion("c_number <>", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberGreaterThan(Integer value) {
            addCriterion("c_number >", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("c_number >=", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberLessThan(Integer value) {
            addCriterion("c_number <", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberLessThanOrEqualTo(Integer value) {
            addCriterion("c_number <=", value, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberIn(List<Integer> values) {
            addCriterion("c_number in", values, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberNotIn(List<Integer> values) {
            addCriterion("c_number not in", values, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberBetween(Integer value1, Integer value2) {
            addCriterion("c_number between", value1, value2, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("c_number not between", value1, value2, "cNumber");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIsNull() {
            addCriterion("c_department is null");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIsNotNull() {
            addCriterion("c_department is not null");
            return (Criteria) this;
        }

        public Criteria andCDepartmentEqualTo(String value) {
            addCriterion("c_department =", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotEqualTo(String value) {
            addCriterion("c_department <>", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentGreaterThan(String value) {
            addCriterion("c_department >", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentGreaterThanOrEqualTo(String value) {
            addCriterion("c_department >=", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLessThan(String value) {
            addCriterion("c_department <", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLessThanOrEqualTo(String value) {
            addCriterion("c_department <=", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentLike(String value) {
            addCriterion("c_department like", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotLike(String value) {
            addCriterion("c_department not like", value, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentIn(List<String> values) {
            addCriterion("c_department in", values, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotIn(List<String> values) {
            addCriterion("c_department not in", values, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentBetween(String value1, String value2) {
            addCriterion("c_department between", value1, value2, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCDepartmentNotBetween(String value1, String value2) {
            addCriterion("c_department not between", value1, value2, "cDepartment");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNull() {
            addCriterion("c_time is null");
            return (Criteria) this;
        }

        public Criteria andCTimeIsNotNull() {
            addCriterion("c_time is not null");
            return (Criteria) this;
        }

        public Criteria andCTimeEqualTo(String value) {
            addCriterion("c_time =", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotEqualTo(String value) {
            addCriterion("c_time <>", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThan(String value) {
            addCriterion("c_time >", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeGreaterThanOrEqualTo(String value) {
            addCriterion("c_time >=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThan(String value) {
            addCriterion("c_time <", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLessThanOrEqualTo(String value) {
            addCriterion("c_time <=", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeLike(String value) {
            addCriterion("c_time like", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotLike(String value) {
            addCriterion("c_time not like", value, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeIn(List<String> values) {
            addCriterion("c_time in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotIn(List<String> values) {
            addCriterion("c_time not in", values, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeBetween(String value1, String value2) {
            addCriterion("c_time between", value1, value2, "cTime");
            return (Criteria) this;
        }

        public Criteria andCTimeNotBetween(String value1, String value2) {
            addCriterion("c_time not between", value1, value2, "cTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazz
     *
     * @mbg.generated do_not_delete_during_merge Mon Mar 25 09:46:42 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}