package com.suse.hl.clazzmenoir.common.domain;

public class Clazz {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.c_id
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    private String cId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.c_name
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    private String cName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.c_number
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    private Integer cNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.c_department
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    private String cDepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clazz.c_time
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    private String cTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public Clazz(String cId, String cName, Integer cNumber, String cDepartment, String cTime) {
        this.cId = cId;
        this.cName = cName;
        this.cNumber = cNumber;
        this.cDepartment = cDepartment;
        this.cTime = cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public Clazz() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.c_id
     *
     * @return the value of clazz.c_id
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public String getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.c_id
     *
     * @param cId the value for clazz.c_id
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setcId(String cId) {
        this.cId = cId == null ? null : cId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.c_name
     *
     * @return the value of clazz.c_name
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.c_name
     *
     * @param cName the value for clazz.c_name
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.c_number
     *
     * @return the value of clazz.c_number
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public Integer getcNumber() {
        return cNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.c_number
     *
     * @param cNumber the value for clazz.c_number
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setcNumber(Integer cNumber) {
        this.cNumber = cNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.c_department
     *
     * @return the value of clazz.c_department
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public String getcDepartment() {
        return cDepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.c_department
     *
     * @param cDepartment the value for clazz.c_department
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setcDepartment(String cDepartment) {
        this.cDepartment = cDepartment == null ? null : cDepartment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clazz.c_time
     *
     * @return the value of clazz.c_time
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public String getcTime() {
        return cTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clazz.c_time
     *
     * @param cTime the value for clazz.c_time
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    public void setcTime(String cTime) {
        this.cTime = cTime == null ? null : cTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Clazz other = (Clazz) that;
        return (this.getcId() == null ? other.getcId() == null : this.getcId().equals(other.getcId()))
            && (this.getcName() == null ? other.getcName() == null : this.getcName().equals(other.getcName()))
            && (this.getcNumber() == null ? other.getcNumber() == null : this.getcNumber().equals(other.getcNumber()))
            && (this.getcDepartment() == null ? other.getcDepartment() == null : this.getcDepartment().equals(other.getcDepartment()))
            && (this.getcTime() == null ? other.getcTime() == null : this.getcTime().equals(other.getcTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcId() == null) ? 0 : getcId().hashCode());
        result = prime * result + ((getcName() == null) ? 0 : getcName().hashCode());
        result = prime * result + ((getcNumber() == null) ? 0 : getcNumber().hashCode());
        result = prime * result + ((getcDepartment() == null) ? 0 : getcDepartment().hashCode());
        result = prime * result + ((getcTime() == null) ? 0 : getcTime().hashCode());
        return result;
    }
}