package com.suse.hl.clazzmenoir.mapper;

import com.suse.hl.clazzmenoir.common.domain.Clazz;
import com.suse.hl.clazzmenoir.common.domain.ClazzExample;
import java.util.List;

import com.suse.hl.clazzmenoir.mapper.extended.ClazzMapperExtend;
import org.apache.ibatis.annotations.Param;

public interface ClazzMapper extends ClazzMapperExtend {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    long countByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int deleteByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int deleteByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int insert(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int insertSelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    List<Clazz> selectByExample(ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    Clazz selectByPrimaryKey(String cId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int updateByExample(@Param("record") Clazz record, @Param("example") ClazzExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int updateByPrimaryKeySelective(Clazz record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clazz
     *
     * @mbg.generated Mon Mar 25 09:46:42 CST 2019
     */
    int updateByPrimaryKey(Clazz record);
}